// Generated by CoffeeScript 1.6.3
(function() {
  var addHostNameToPreviewDiv, addLoadingSpinnerToPreview, addPreviewDiv, addPreviewNode, addSmallScreenshotToPreview, addTemporaryComputerIcon, addTestSlots, curentUrl, hideLoadingSpinnerFromPreview, sanitizeScreenshot, setupPreviewNodes;

  jQuery.noConflict();

  curentUrl = window.location.pathname;

  sanitizeScreenshot = function(image) {
    return image.gsub(/[\\\"\[\]]/, "");
  };

  addPreviewDiv = function(node) {
    var li;
    li = "<li><div id='" + Strings.sanitizeId(node.host) + "' class='node-list'><div class='small-screenshot'></div><dl class='node-info'></dl><div class='spinner'></div></li>";
    return jQuery(getNodeListDiv()).append(li);
  };

  addTemporaryComputerIcon = function(ip) {
    var tempIcon;
    tempIcon = "<img class='temp-screenshot' src='/plugin/SeleniumGridExtras-plugin/images/computer.png'/>";
    return jQuery(getSmallScreenshotDiv(ip)).append(tempIcon);
  };

  addHostNameToPreviewDiv = function(ip) {
    return jQuery(getNodeInfoDiv(ip)).append("<dt>Host</dt><dd>" + ip + "</dd>");
  };

  addLoadingSpinnerToPreview = function(node) {
    var spinnerImage;
    spinnerImage = "<img src='/plugin/SeleniumGridExtras-plugin/images/loading.gif'/>";
    return jQuery(getPreviewSpinner(ip)).append(spinnerImage);
  };

  hideLoadingSpinnerFromPreview = function(ip) {
    return jQuery(getPreviewSpinner(ip)).hide();
  };

  addSmallScreenshotToPreview = function(ip) {
    return jQuery.ajax(curentUrl + "screenshot?width=200&height=100&keep=false&ip=" + ip, {
      type: 'GET',
      dataType: 'json',
      success: function(screenshot, textStatus, jqXHR) {
        var actualScreenshot;
        actualScreenshot = "<img class='actual-screenshot' src='data:image/png;base64,";
        actualScreenshot = actualScreenshot + sanitizeScreenshot(screenshot.image);
        actualScreenshot = actualScreenshot + "' >";
        jQuery(getPreviewTempScreenshot(ip)).hide();
        return jQuery(getSmallScreenshotDiv(ip)).append(actualScreenshot);
      }
    });
  };

  addTestSlots = function(node) {
    var gridTestSlots, slot, _i, _len, _ref;
    gridTestSlots = new TestSlots;
    _ref = node.slots;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      slot = _ref[_i];
      gridTestSlots.addSlot(slot.browserName, slot);
    }
    return jQuery(getNodeInfoDiv(node.host)).append(gridTestSlots.getHtml());
  };

  addPreviewNode = function(node) {
    addPreviewDiv(node);
    addTemporaryComputerIcon(node.host);
    addHostNameToPreviewDiv(node.host);
    addSmallScreenshotToPreview(node.host);
    addTestSlots(node);
    return hideLoadingSpinnerFromPreview(node.host);
  };

  setupPreviewNodes = function(callback) {
    var nodeArray;
    nodeArray = [];
    return jQuery.ajax(curentUrl + "nodes", {
      type: 'GET',
      dataType: 'json',
      error: function(jqXHR, textStatus, errorThrown) {
        return alert("Something went wrong getting nodes - AJAX Error:" + textStatus);
      },
      success: function(returnedNodes, textStatus, jqXHR) {
        var node, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = returnedNodes.length; _i < _len; _i++) {
          node = returnedNodes[_i];
          nodeArray.push(node);
          _results.push(callback(returnedNodes));
        }
        return _results;
      }
    });
  };

  jQuery('document').ready(function() {
    return setupPreviewNodes(function(nodes) {
      var node, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = nodes.length; _i < _len; _i++) {
        node = nodes[_i];
        _results.push(addPreviewNode(node));
      }
      return _results;
    });
  });

}).call(this);
