// Generated by CoffeeScript 1.6.3
(function() {
  var addFullScreenshot, addHostNameToPreviewDiv, addLoadingSpinnerToPreview, addPreviewDiv, addPreviewNode, addSmallScreenshotToPreview, addTemporaryComputerIcon, addTestSlots, addTestSlotsStatus, attachFullScreenshotTrigger, curentUrl, hideLoadingSpinnerFromPreview, sanitizeScreenshot, setupPreviewNodes;

  jQuery.noConflict();

  curentUrl = window.location.pathname;

  sanitizeScreenshot = function(image) {
    return image.gsub(/[\\\"\[\]]/, "");
  };

  addPreviewDiv = function(node) {
    var li;
    li = "<li><div id='" + Strings.sanitizeId(node.host) + "' class='node-list'><div class='small-screenshot'></div><dl class='node-info'></dl><div class='spinner'></div></li>";
    return jQuery(getNodeListDiv()).append(li);
  };

  addTemporaryComputerIcon = function(ip) {
    var tempIcon;
    tempIcon = "<img class='temp-screenshot' src='/plugin/SeleniumGridExtras-plugin/images/computer.png'/>";
    return jQuery(getSmallScreenshotDiv(ip)).append(tempIcon);
  };

  addHostNameToPreviewDiv = function(ip) {
    return jQuery(getNodeInfoDiv(ip)).append("<dt>Host</dt><dd>" + ip + "</dd>");
  };

  addLoadingSpinnerToPreview = function(node) {
    var spinnerImage;
    spinnerImage = "<img src='/plugin/SeleniumGridExtras-plugin/images/loading.gif'/>";
    return jQuery(getPreviewSpinner(ip)).append(spinnerImage);
  };

  hideLoadingSpinnerFromPreview = function(ip) {
    return jQuery(getPreviewSpinner(ip)).hide();
  };

  addSmallScreenshotToPreview = function(ip, width, height) {
    return jQuery.ajax(curentUrl + "screenshot?width=" + width + "&height=" + height + "&keep=false&ip=" + ip, {
      type: 'GET',
      dataType: 'json',
      success: function(screenshot, textStatus, jqXHR) {
        var actualScreenshot;
        actualScreenshot = "<img class='actual-screenshot' src='data:image/png;base64,";
        actualScreenshot = actualScreenshot + sanitizeScreenshot(screenshot.image);
        actualScreenshot = actualScreenshot + "' >";
        jQuery(getPreviewTempScreenshot(ip)).hide();
        return jQuery(getSmallScreenshotDiv(ip)).append(actualScreenshot);
      }
    });
  };

  addFullScreenshot = function(ip, width, height) {
    return jQuery.ajax(curentUrl + "screenshot?width=" + width + "&height=" + height + "&keep=false&ip=" + ip, {
      type: 'GET',
      dataType: 'json',
      success: function(screenshot, textStatus, jqXHR) {
        var actualScreenshot;
        actualScreenshot = "<img class='full-screenshot' src='data:image/png;base64,";
        actualScreenshot = actualScreenshot + sanitizeScreenshot(screenshot.image);
        actualScreenshot = actualScreenshot + "' >";
        jQuery(getLargeScreenshotDiv() + " img").remove();
        return jQuery(getLargeScreenshotDiv()).append(actualScreenshot);
      }
    });
  };

  addTestSlots = function(node) {
    var gridTestSlots, slot, _i, _len, _ref;
    gridTestSlots = new TestSlots;
    _ref = node.slots;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      slot = _ref[_i];
      gridTestSlots.addSlot(slot.browserName, slot);
    }
    return jQuery(getNodeInfoDiv(node.host)).append(gridTestSlots.getHtml());
  };

  addTestSlotsStatus = function(node) {
    var slot, status, _i, _len, _ref;
    status = "idle";
    _ref = node.slots;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      slot = _ref[_i];
      if (slot.session !== "") {
        status = "busy";
      }
    }
    return jQuery(getNodeInfoDiv(node.host)).append("<dt>Status</dt><dd>" + status + "</dd>");
  };

  attachFullScreenshotTrigger = function(ip) {
    console.log("attaching screenshot get event to " + ip);
    return jQuery(getPreviewDiv(ip)).click(function() {
      console.log("Clicked on " + ip + " now getting full screenshot");
      return addFullScreenshot(ip, 768, 1024);
    });
  };

  addPreviewNode = function(node) {
    addPreviewDiv(node);
    addTemporaryComputerIcon(node.host);
    addHostNameToPreviewDiv(node.host);
    addSmallScreenshotToPreview(node.host, 200, 100);
    attachFullScreenshotTrigger(node.host);
    addTestSlotsStatus(node);
    return hideLoadingSpinnerFromPreview(node.host);
  };

  setupPreviewNodes = function(callback) {
    return jQuery.ajax(curentUrl + "nodes", {
      type: 'GET',
      dataType: 'json',
      error: function(jqXHR, textStatus, errorThrown) {
        return alert("Something went wrong getting nodes - AJAX Error:" + textStatus);
      },
      success: function(returnedNodes, textStatus, jqXHR) {
        return callback(returnedNodes);
      }
    });
  };

  jQuery('document').ready(function() {
    return setupPreviewNodes(function(nodes) {
      var node, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = nodes.length; _i < _len; _i++) {
        node = nodes[_i];
        console.log("Working on " + node.host);
        _results.push(addPreviewNode(node));
      }
      return _results;
    });
  });

}).call(this);
