// Generated by CoffeeScript 1.6.3
(function() {
  var sanitizeId;

  sanitizeId = function(ip) {
    return Strings.sanitizeId(ip);
  };

  window.getNodeListDiv = function() {
    return "#node_list";
  };

  window.getPreviewDiv = function(ip) {
    return "#" + sanitizeId(ip);
  };

  window.getSmallScreenshotDiv = function(ip) {
    return getPreviewDiv(ip) + " .small-screenshot";
  };

  window.getNodeInfoDiv = function(ip) {
    return getPreviewDiv(ip) + " .node-info";
  };

  window.getPreviewSpinner = function(ip) {
    return getPreviewDiv(ip) + " .spinner";
  };

  window.getPreviewTempScreenshot = function(ip) {
    return getPreviewDiv(ip) + " .small-screenshot .temp-screenshot";
  };

  window.getLargeScreenshotDiv = function() {
    return "#largeScreenshot";
  };

}).call(this);
