// Generated by CoffeeScript 1.6.3
(function() {
  var BrowserIcon, TestSlots;

  window.BrowserIcon = BrowserIcon = (function() {
    function BrowserIcon() {}

    BrowserIcon.getBrowserIcon = function(browser) {
      switch (browser) {
        case "firefox":
          return "firefox.png";
        case "chrome":
          return "chrome.png";
        case "internet explorer":
          return "internet_explorer.png";
        default:
          return "firefox.png";
      }
    };

    return BrowserIcon;

  })();

  window.TestSlots = TestSlots = (function() {
    var SLOTS_BY_BROWSER;

    SLOTS_BY_BROWSER = {};

    function TestSlots() {}

    TestSlots.prototype.addSlot = function(browser, slot) {
      if (SLOTS_BY_BROWSER[browser] == null) {
        SLOTS_BY_BROWSER[browser] = {
          used: 0,
          total: 0
        };
      }
      if (slot.session === "") {
        return SLOTS_BY_BROWSER[browser].total = SLOTS_BY_BROWSER[browser].total + 1;
      } else {
        SLOTS_BY_BROWSER[browser].total = SLOTS_BY_BROWSER[browser].total + 1;
        return SLOTS_BY_BROWSER[browser].used = SLOTS_BY_BROWSER[browser].used + 1;
      }
    };

    TestSlots.prototype.getHtml = function() {
      var browser, html, keys, _i, _len;
      keys = Object.keys(SLOTS_BY_BROWSER);
      console.log(keys);
      html = "<dt class='test-slots'>Used</dt>";
      html = html + "<dd><dl>";
      for (_i = 0, _len = keys.length; _i < _len; _i++) {
        browser = keys[_i];
        html = html + "<dt><img class='browser-icon' src='/plugin/SeleniumGridExtras-plugin/images/";
        html = html + BrowserIcon.getBrowserIcon(browser) + "' /></dt>";
        html = html + "<dd>";
        html = html + SLOTS_BY_BROWSER[browser].used + "/" + SLOTS_BY_BROWSER[browser].total;
        html = html + "</dd>";
      }
      html = html + "</dl></dd>";
      return html;
    };

    TestSlots.prototype.getSlot = function(slot) {
      return SLOTS_BY_BROWSER[slot];
    };

    return TestSlots;

  })();

}).call(this);
